# Generated by Django 5.1.6 on 2025-02-20 11:00

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_departmentpage'),
        ('wagtailcore', '0094_alter_page_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDepartmentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(max_length=100)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('site_admins', modelcluster.fields.ParentalManyToManyField(blank=True, limit_choices_to={'is_superuser': False}, related_name='administered_subdepartments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sub Department',
                'verbose_name_plural': 'Sub Departments',
            },
            bases=('wagtailcore.page',),
        ),
    ]
